Clientes/urls.py
from django.urls import path
from . import views

app_name = 'clientes'

urlpatterns = [
    path('detalle/<int:pk>/', views.detalle_cliente, name='detalle_cliente'),
    path('lista_clientes/', views.lista_clientes, name='lista_clientes'),



    path('seleccionar/', views.seleccionar_crud_cliente, name='seleccionar_crud_cliente'),

    path('crear/', views.crear_cliente, name='crear_cliente'),
    path('lista/', views.lista_clientes, name='lista_clientes'),
    path('editar/<int:pk>/', views.editar_cliente, name='editar_cliente'),
    path('eliminar/<int:pk>/', views.eliminar_cliente, name='eliminar_cliente'),

]

pedidos/urls.py
from django.urls import path
from . import views

app_name = 'pedidos'

urlpatterns = [
    path('', views.pedido_home, name='home'),

    path('seleccionarCrud/', views.seleccionar_crud_pedido, name='seleccionar_crud_pedido'),

    path('crear-pedido/', views.crear_pedido, name='crear_pedido'),
    path('lista-pedidos/', views.pedido_home, name='pedido_home'),
    path('editar-pedido/<int:pk>/', views.editar_pedido, name='editar_pedido'),
    path('detalle-pedido/<int:pk>/', views.detalle_pedido, name='detalle_pedido'),
    path('eliminar-pedido/<int:pedido_id>/', views.eliminar_pedido, name='eliminar_pedido'),
]

proyectoevaluacion/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usuarios.urls')),
    path('clientes/', include('Clientes.urls')),
    path('inventario/', include('inventario.urls')),
    path('pedidos/', include('pedidos.urls')),
    

]

Clientes/models.py
from django.db import models
from django.contrib.auth.models import User

class Cliente(models.Model):
    nombre = models.CharField(max_length=200)
    direccion = models.TextField()
    email = models.CharField(max_length=254, unique=True)
    telefono = models.CharField(max_length=20)
    fecha_registro = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nombre

Clientes/forms.py
from django import forms
from .models import Cliente

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['nombre','direccion', 'email', 'telefono']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'direccion': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'telefono': forms.TextInput(attrs={'class': 'form-control'}),
            
        }

Clientes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Cliente
from .forms import ClienteForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
# Create your views here.

@login_required
def seleccionar_crud_cliente(request):
    if request.user.perfil.rol in ['tecnico', 'administrador']:
        clientes = Cliente.objects.all()  
        return render(request, 'Clientes/seleccionar_crud_cliente.html', {'clientes': clientes})
    else:
        return redirect('Clientes:lista_clientes')  

@login_required
def lista_clientes(request):
    q = request.GET.get('q', '')
    if q:
        clientes = Cliente.objects.filter(
            Q(nombre__icontains=q) | Q(direccion__icontains=q) | Q(email__icontains=q) | Q(telefono__icontains=q)
        )
    else:
        clientes = Cliente.objects.all()
    return render(request, 'clientes/lista_clientes.html', {'clientes': clientes, 'q': q})

@login_required
def crear_cliente(request):
    if request.user.perfil.rol in ['administrador']:
        if request.method == 'POST':
            form = ClienteForm(request.POST)
            if form.is_valid():
                cliente = form.save(commit=False)
                cliente.save() 
                return redirect('clientes:detalle_cliente', pk=cliente.pk)
        else:
            form = ClienteForm()
        return render(request, 'Clientes/crear_cliente.html', {'form': form})
    else:
        return redirect('clientes:lista_clientes')

@login_required
def detalle_cliente(request, pk):
    if request.user.perfil.rol in ['tecnico', 'administrador']:
        cliente = get_object_or_404(Cliente, pk=pk)
        return render(request, 'Clientes/detalle_cliente.html', {'cliente': cliente})


@login_required
def editar_cliente(request, pk):
    cliente = get_object_or_404(Cliente, pk=pk)
    if request.user.perfil.rol in ['administrador']:
        if request.method == 'POST':
            form = ClienteForm(request.POST, instance=cliente)
            if form.is_valid():
                form.save()
                messages.success(request, '¡Cambios guardados exitosamente!', extra_tags='cliente')
                return redirect('clientes:lista_clientes')
        else:
            form = ClienteForm(instance=cliente)
        return render(request, 'Clientes/editar_cliente.html', {'form': form})
    else:
        return redirect('clientes:lista_clientes')

@login_required
def eliminar_cliente(request, pk):
    if request.user.perfil.rol in ['administrador']:
        cliente = get_object_or_404(Cliente, pk=pk)
    if request.method == 'POST':
        cliente.delete()
        return redirect('clientes:lista_clientes')
    return render(request, 'Clientes/eliminar_cliente.html', {'cliente': cliente})

Clientes/templates/Clientes/crear_cliente.html
{% extends 'base.html' %}
{% block title %}Crear Cliente{% endblock %}
{% block content %}
<div class="container mt-4 form-container">
    <h2>Crear Nuevo Cliente</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}

        <div class="form-group">
            <label for="id_nombre">Nombre:</label>
            {{ form.nombre.errors }}
            {{ form.nombre }}
        </div>

        <div class="form-group">
            <label for="id_direccion">Dirección:</label>
            {{ form.direccion.errors }}
            {{ form.direccion }}
        </div>

        <div class="form-group">
            <label for="id_email">Email:</label>
            {{ form.email.errors }}
            {{ form.email }}
        </div>

        <div class="form-group">
            <label for="id_telefono">Teléfono:</label>
            {{ form.telefono.errors }}
            {{ form.telefono }}
        </div>

        <div class="form-group">
            <label for="id_fecha_registro">Fecha de Registro:</label>
            {{ form.fecha_registro.errors }}
            {{ form.fecha_registro }}
        </div>

        <button type="submit" class="btn btn-primary">Guardar Cliente</button>
    </form>
</div>
{% endblock %}

Clientes/templates/Clientes/detalle_cliente.html
{% extends 'base.html' %}
{% block title %}{{ cliente.nombre }}{% endblock %}
{% block content %}
<div class="container mt-4 form-container">
    <h2>Detalles de {{ cliente.nombre }}</h2>
    <hr>
    <p><strong>Dirección:</strong> {{ cliente.direccion }}</p>
    <p><strong>Email:</strong> {{ cliente.email }}</p>
    <p><strong>Teléfono:</strong> {{ cliente.telefono }}</p>
    <p><strong>Fecha de Registro:</strong> {{ cliente.fecha_registro }}</p>

    {% if request.user.is_authenticated and request.user.perfil.rol == 'administrador' %}
        <a href="{% url 'clientes:editar_cliente' cliente.pk %}" class="btn btn-primary">Editar Cliente</a>
    {% endif %}
    <a href="{% url 'clientes:lista_clientes' %}" class="btn btn-link">Volver a la lista de clientes</a>
</div>
{% endblock %}

Clientes/templates/Clientes/editar_cliente.html
{% extends 'base.html' %}
{% block title %}Editar Cliente{% endblock %}
{% block content %}
<div class="container mt-4 form-container">
    <h2>Editar Cliente</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}

        <div class="form-group">
            <label for="id_nombre">Nombre:</label>
            {{ form.nombre.errors }}
            {{ form.nombre }}
        </div>

        <div class="form-group">
            <label for="id_direccion">Dirección:</label>
            {{ form.direccion.errors }}
            {{ form.direccion }}
        </div>

        <div class="form-group">
            <label for="id_email">Email:</label>
            {{ form.email.errors }}
            {{ form.email }}
        </div>

        <div class="form-group">
            <label for="id_telefono">Teléfono:</label>
            {{ form.telefono.errors }}
            {{ form.telefono }}
        </div>
        <button type="submit" class="btn btn-primary">Guardar Cambios</button>
    </form>
</div>
{% endblock %}

Clientes/templates/Clientes/eliminar_cliente.html
{% extends 'base.html' %}
{% block title %}Eliminar Cliente{% endblock %}
{% block content %}

<div class="container mt-4">

    <h2>Detalles de {{ cliente.nombre }}</h2>
    <hr>
    <p><strong>Dirección:</strong> {{ cliente.direccion }}</p>
    <p><strong>Email:</strong> {{ cliente.email }}</p>
    <p><strong>Teléfono:</strong> {{ cliente.telefono }}</p>
    <p><strong>Fecha de Registro:</strong> {{ cliente.fecha_registro }}</p>


    <h2>Eliminar Cliente</h2>
    <p>¿Estás seguro de que deseas eliminar a <strong>{{ cliente.nombre }}</strong>?</p>
    <p>Esta acción no se puede deshacer.</p>

    <form method="post" action="{% url 'clientes:eliminar_cliente' cliente.pk %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Eliminar</button>
        <a href="{% url 'clientes:lista_clientes' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>


{% endblock %}

Clientes/templates/Clientes/lista_clientes.html
{% extends 'base.html' %}
{% block title %}Clientes{% endblock %}
{% block content %}



<div class="container mt-4 form-container">

    {% if messages %}
        {% for message in messages %}
            {% if 'cliente' in message.tags %}
                <div class="alert alert-success" role="alert">
                    {{ message }}
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}

    <form method="get" class="mb-3">
        <input type="text" name="q" class="form-control" placeholder="Buscar cliente..." value="{{ q }}">
        <button type="submit" class="btn btn-primary mt-2">Buscar</button>
    </form>

    <h2>Lista de Clientes</h2>
    {% if request.user.is_authenticated %}
        {% if request.user.perfil.rol == 'tecnico' or request.user.perfil.rol == 'administrador' %}
            <a href="{% url 'clientes:crear_cliente' %}" class="btn btn-success mb-3">Crear Cliente</a>
            <a href="{% url 'clientes:seleccionar_crud_cliente' %}" class="btn btn-info">Volver a la Gestión de Clientes</a>
        {% endif %}
    {% endif %}
    
    {% for cliente in clientes %}
        <div class="card mb-3 caja-cliente">
            <div class="card-body">
                <h5 class="card-title">{{ cliente.nombre }}</h5>
                <p class="card-text">
                    Dirección: {{ cliente.direccion }} <br>
                    Teléfono: {{ cliente.telefono }} <br>
                    Email: {{ cliente.email }}

                   

                    {% if user.perfil.rol == 'administrador' %}
                    <div class="container mt-4">
                        <form method="post" action="{% url 'clientes:eliminar_cliente' cliente.pk %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Eliminar</button>
                        </form>
                    </div>
                    {% endif %}
                </p>
                <a href="{% url 'clientes:detalle_cliente' cliente.pk %}" class="btn btn-primary">Ver Detalles</a>
            </div>
        </div>
    {% empty %}
        <p>No hay clientes disponibles.</p>
    {% endfor %}
</div>
{% endblock %}

Clientes/templates/Clientes/seleccionar_crud_cliente.html
{% extends 'base.html' %}
{% block title %}Menú de Clientes{% endblock %}
{% block content %}


<div class="form-container">
    <h2>Seleccione una acción</h2>
    <p>Elija una de las siguientes acciones para gestionar los clientes:</p>
    
    <div class="d-flex justify-content-around mt-4">
        <a href="{% url 'clientes:crear_cliente' %}" class="btn btn-success">Crear Cliente</a>
       
        <a href="{% url 'clientes:lista_clientes' %}" class="btn btn-primary">Ver Clientes (Permite elminar y editar datos)</a>
       
    </div>
</div>








{% endblock %}