pedidos/urls.py
from django.urls import path
from . import views

app_name = 'pedidos'

urlpatterns = [
    path('', views.pedido_home, name='home'),

    path('seleccionarCrud/', views.seleccionar_crud_pedido, name='seleccionar_crud_pedido'),

    path('crear-pedido/', views.crear_pedido, name='crear_pedido'),
    path('lista-pedidos/', views.pedido_home, name='pedido_home'),
    path('editar-pedido/<int:pk>/', views.editar_pedido, name='editar_pedido'),
    path('detalle-pedido/<int:pk>/', views.detalle_pedido, name='detalle_pedido'),
    path('eliminar-pedido/<int:pedido_id>/', views.eliminar_pedido, name='eliminar_pedido'),
]

proyectoevaluacion/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usuarios.urls')),
    path('clientes/', include('Clientes.urls')),
    path('inventario/', include('inventario.urls')),
    path('pedidos/', include('pedidos.urls')),
    

]

pedidos/models.py
from django.db import models
from django.db import models
from Clientes.models import Cliente
from inventario.models import Extintor

# Create your models here.

class Pedido(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    item_inventario = models.ForeignKey(Extintor, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField(default=1)
    fecha_entrega = models.DateField(null=True, blank=True)

    def __str__(self):
        return f"Pedido {self.id} - Cliente: {self.cliente.nombre}"

pedidos/forms.py
from django import forms
from .models import Pedido

class PedidoForm(forms.ModelForm):
    class Meta:
        model = Pedido
        fields = ['cliente', 'item_inventario', 'cantidad', 'fecha_entrega']
        widgets = {
            'cliente': forms.Select(attrs={'class': 'form-control'}),
            'item_inventario': forms.Select(attrs={'class': 'form-control'}),
            'cantidad': forms.NumberInput(attrs={'class': 'form-control'}),
            'fecha_entrega': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
        }

pedidos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Pedido
from .forms import PedidoForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q

# Create your views here.

@login_required
def seleccionar_crud_pedido(request):
    if request.user.perfil.rol in ['tecnico', 'administrador']:
        pedidos = Pedido.objects.all()  
        return render(request, 'pedidos/seleccionar_crud_pedido.html', {'pedidos': pedidos})
    else:
        return redirect('pedidos:pedido_home') 

@login_required
def pedido_home(request):
    query = request.GET.get('q')
    if query:
        pedidos = Pedido.objects.filter(
            Q(cliente__nombre__icontains=query) |
            Q(item_inventario__nombre__icontains=query)
        )
    else:
        pedidos = Pedido.objects.all()
    return render(request, 'pedidos/pedido_home.html', {'pedidos': pedidos})

# crear el pedido
@login_required
def crear_pedido(request):
    if request.user.perfil.rol in ['administrador', 'tecnico']:
        if request.method == 'POST':
            form = PedidoForm(request.POST)
            if form.is_valid():
                pedido = form.save(commit=False)
                pedido.save()
                messages.success(request, 'Pedido creado exitosamente')
                return redirect('pedidos:pedido_home')
        else:
            form = PedidoForm()
        return render(request, 'pedidos/crear_pedido.html', {'form': form})
    else:
        return redirect('pedidos:pedido_home')


@login_required
def detalle_pedido(request, pk):
    if request.user.perfil.rol in ['tecnico', 'administrador']:
        pedido = get_object_or_404(Pedido, pk=pk)
        return render(request, 'pedidos/detalle_pedido.html', {'pedido': pedido})
    else:
        return redirect('pedidos:pedido_home')


@login_required
def editar_pedido(request, pk):
    pedido = get_object_or_404(Pedido, pk=pk)
    if request.user.perfil.rol in ['administrador', 'tecnico']:
        if request.method == 'POST':
            form = PedidoForm(request.POST, instance=pedido)
            if form.is_valid():
                form.save()
                messages.success(request, 'Pedido actualizado exitosamente')
                return redirect('pedidos:pedido_home')
        else:
            form = PedidoForm(instance=pedido)
        return render(request, 'pedidos/editar_pedido.html', {'form': form})
    else:
        return redirect('pedidos:pedido_home')


@login_required
def eliminar_pedido(request, pedido_id):
    pedido = Pedido.objects.get(id=pedido_id)
    pedido.delete();
    return redirect('pedidos:pedido_home')

pedidos/templates/pedidos/crear_pedido.html
{% extends 'base.html' %}
{% block title %}Crear Pedido{% endblock %}
{% block content %}
<div class="container mt-4 form-container">
    <h2>Crear Nuevo Pedido</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}

        <div class="form-group">
            <label for="id_cliente">Cliente:</label>
            {{ form.cliente.errors }}
            {{ form.cliente }}
        </div>

        <div class="form-group">
            <label for="id_item_inventario">Item de Inventario:</label>
            {{ form.item_inventario.errors }}
            {{ form.item_inventario }}
        </div>

        <div class="form-group">
            <label for="id_cantidad">Cantidad:</label>
            {{ form.cantidad.errors }}
            {{ form.cantidad }}
        </div>

        <div class="form-group">
            <label for="id_fecha_entrega">Fecha de Entrega:</label>
            {{ form.fecha_entrega.errors }}
            {{ form.fecha_entrega }}
        </div>

        <button type="submit" class="btn btn-primary">Guardar Pedido</button>
    </form>
</div>
{% endblock %}

pedidos/templates/pedidos/detalle_pedido.html
{% extends 'base.html' %}
{% block title %}Detalles del Pedido #{{ pedido.id }}{% endblock %}
{% block content %}
<div class="container mt-4 form-container">
    <h2>Detalles del Pedido #{{ pedido.id }}</h2>
    <hr>
    <p><strong>Cliente:</strong> {{ pedido.cliente.nombre }}</p>
    <p><strong>Item de Inventario:</strong> {{ pedido.item_inventario.nombre }}</p>
    <p><strong>Cantidad:</strong> {{ pedido.cantidad }}</p>
    <p><strong>Fecha de Entrega:</strong> {{ pedido.fecha_entrega }}</p>

    {% if request.user.is_authenticated and request.user.perfil.rol == 'administrador' or request.user.perfil.rol == 'tecnico' %}
        <a href="{% url 'pedidos:editar_pedido' pedido.id %}" class="btn btn-primary">Editar Pedido</a>
    {% endif %}
    <a href="{% url 'pedidos:pedido_home' %}" class="btn btn-link">Volver a la lista de pedidos</a>
</div>
{% endblock %}

pedidos/templates/pedidos/editar_pedido.html
{% extends 'base.html' %}
{% block title %}Editar Pedido{% endblock %}
{% block content %}
<div class="container mt-4 form-container">
    <h2>Editar Pedido</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}

        <div class="form-group">
            <label for="id_cliente">Cliente:</label>
            {{ form.cliente.errors }}
            {{ form.cliente }}
        </div>

        <div class="form-group">
            <label for="id_item_inventario">Item de Inventario:</label>
            {{ form.item_inventario.errors }}
            {{ form.item_inventario }}
        </div>

        <div class="form-group">
            <label for="id_cantidad">Cantidad:</label>
            {{ form.cantidad.errors }}
            {{ form.cantidad }}
        </div>

        <div class="form-group">
            <label for="id_fecha_entrega">Fecha de Entrega:</label>
            {{ form.fecha_entrega.errors }}
            {{ form.fecha_entrega }}
        </div>

        <button type="submit" class="btn btn-primary">Guardar Cambios</button>
    </form>
</div>
{% endblock %}

pedidos/templates/pedidos/pedido_home.html
{% extends 'base.html' %}
{% block title %}Pedidos{% endblock %}
{% block content %}

<div class="container mt-4 form-container">
    {% if messages %}
        {% for message in messages %}
            {% if 'pedidos' in message.tags %}
                <div class="alert alert-success" role="alert">
                    {{ message }}
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}

    <h2>Lista de Pedidos</h2>
    {% if request.user.is_authenticated %}
        {% if request.user.perfil.rol == 'tecnico' or request.user.perfil.rol == 'administrador' %}
            <a href="{% url 'pedidos:crear_pedido' %}" class="btn btn-success mb-3">Agregar Pedido</a>
            <a href="{% url 'pedidos:seleccionar_crud_pedido' %}" class="btn btn-info">Volver a la Gestión de Pedidos</a>
        {% endif %}
    {% endif %}
    
     <form method="get" action="{% url 'pedidos:pedido_home' %}" class="mb-3">
        <input type="text" name="q" class="form-control" placeholder="Buscar pedidos...">
        <button type="submit" class="btn btn-primary mt-2">Buscar</button>
    </form>

    {% for pedido in pedidos %}
        <div class="card mb-3 caja-pedido">
            <div class="card-body">
                <h5 class="card-title">Pedido de {{ pedido.cliente.nombre }}</h5>
                <p class="card-text">
                    Item: {{ pedido.item_inventario.nombre }} <br>
                    Cantidad: {{ pedido.cantidad }} <br>
                    Fecha de Entrega: {{ pedido.fecha_entrega|date:"d/m/Y" }}
                </p>
                {% if request.user.perfil.rol == 'administrador' or request.user.perfil.rol == 'tecnico' %}
                    <div class="container mt-4">
                        <form method="post" action="{% url 'pedidos:eliminar_pedido' pedido.pk %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Eliminar</button>
                        </form>
                    </div>
                {% endif %}

                <a href="{% url 'pedidos:detalle_pedido' pedido.pk %}" class="btn btn-primary">Ver Detalles</a>
            </div>
        </div>
    {% empty %}
        <p>No hay pedidos registrados.</p>
    {% endfor %}
</div>
{% endblock %}

pedidos/templates/pedidos/seleccionar_crud_pedido.html
{% extends 'base.html' %}
{% block title %}Menú de Pedidos{% endblock %}
{% block content %}

<div class="form-container">
    <h2>Seleccione una acción</h2>
    <p>Elija una de las siguientes acciones para gestionar los Pedidos:</p>
    
    <div class="d-flex justify-content-around mt-4">
        <a href="{% url 'pedidos:crear_pedido' %}" class="btn btn-success">Crear Pedido</a>
       
        <a href="{% url 'pedidos:pedido_home' %}" class="btn btn-primary">Ver Pedidos (Permite eliminar y editar datos)</a>
       
    </div>
</div>

{% endblock %}