inventario/urls.py
from django.urls import path
from . import views

app_name = 'inventario'

urlpatterns = [
    path('', views.inventario_home, name='home'),

    path('seleccionarCrud/', views.seleccionar_crud_inventario, name='seleccionar_crud_inventario'),

    path('crear-item/', views.crear_extintor, name='crear_extintor'),
    path('lista-inventario/', views.inventario_home, name='inventario_home'),
    path('editar-item/<int:pk>/', views.editar_extintor, name='editar_extintor'),
    path('detalle-item/<int:pk>/', views.detalle_extintor, name='detalle_extintor'),
    path('eliminar-extintor/<int:extintor_id>/', views.eliminar_extintor, name='eliminar_extintor'),

]

pedidos/urls.py
from django.urls import path
from . import views

app_name = 'pedidos'

urlpatterns = [
    path('', views.pedido_home, name='home'),

    path('seleccionarCrud/', views.seleccionar_crud_pedido, name='seleccionar_crud_pedido'),

    path('crear-pedido/', views.crear_pedido, name='crear_pedido'),
    path('lista-pedidos/', views.pedido_home, name='pedido_home'),
    path('editar-pedido/<int:pk>/', views.editar_pedido, name='editar_pedido'),
    path('detalle-pedido/<int:pk>/', views.detalle_pedido, name='detalle_pedido'),
    path('eliminar-pedido/<int:pedido_id>/', views.eliminar_pedido, name='eliminar_pedido'),
]

proyectoevaluacion/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usuarios.urls')),
    path('clientes/', include('Clientes.urls')),
    path('inventario/', include('inventario.urls')),
    path('pedidos/', include('pedidos.urls')),
    

]

inventario/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Extintor(models.Model):
    nombre = models.CharField(max_length=200)
    tipo = models.TextField()
    cantidad = models.IntegerField()


    def __str__(self):
        return self.nombre

inventario/forms.py
from django import forms
from .models import Extintor

class ExtintorForm(forms.ModelForm):
    class Meta:
        model = Extintor
        fields = ['nombre', 'tipo', 'cantidad']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'tipo': forms.TextInput(attrs={'class': 'form-control'}),
            'cantidad': forms.NumberInput(attrs={'class': 'form-control'}),
        }

inventario/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.shortcuts import render
from django.shortcuts import render, redirect
from .models import Extintor
from .forms import ExtintorForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q

# Create your views here.

@login_required
def seleccionar_crud_inventario(request):
    if request.user.perfil.rol in ['tecnico', 'administrador']:
        extintores = Extintor.objects.all()  
        return render(request, 'inventario/seleccionar_crud_inventario.html', {'extintores': extintores})
    else:
        return redirect('inventario:lista_clientes')  

#.......LISTA de Items..........
@login_required
def inventario_home(request):
    q = request.GET.get('q', '')
    if q:
        extintores = Extintor.objects.filter(
            Q(nombre__icontains=q) | Q(tipo__icontains=q)
        )
    else:
        extintores = Extintor.objects.all()
    return render(request, 'inventario/inventario_home.html', {'extintores': extintores, 'q': q})

#................vista para crear inventario...................
@login_required
def crear_extintor(request):
    if request.user.perfil.rol in ['administrador', 'tecnico']:
        if request.method == 'POST':
            form = ExtintorForm(request.POST)
            if form.is_valid():
                Extintor = form.save(commit=False)
                Extintor.save() 
                return redirect('inventario:detalle_extintor', pk=Extintor.pk)
        else:
            form = ExtintorForm()
        return render(request, 'Inventario/crear_extintor.html', {'form': form})
    else:
        return redirect('inventario:inventario_home')


#........Ventana de detalles........
@login_required
def detalle_extintor(request, pk):
    if request.user.perfil.rol in ['tecnico', 'administrador']:
        extintor = get_object_or_404(Extintor, pk=pk)
        return render(request, 'inventario/detalle_extintor.html', {'extintor': extintor})

@login_required
def editar_extintor(request, pk):
    extintor = get_object_or_404(Extintor, pk=pk)
    if request.user.perfil.rol in ['administrador', 'tecnico']:
        if request.method == 'POST':
            form = ExtintorForm(request.POST, instance=extintor)
            if form.is_valid():
                form.save()
                messages.success(request, '¡Cambios guardados exitosamente!', extra_tags='cliente')
                return redirect('inventario:inventario_home')
        else:
            form = ExtintorForm(instance=extintor)
        return render(request, 'Inventario/editar_extintor.html', {'form': form})
    else:
        return redirect('inventario:inventario_home')



@login_required
def eliminar_extintor(request, extintor_id):
    extintor = Extintor.objects.get(id=extintor_id)
    extintor.delete()
    return redirect('inventario:inventario_home')

inventario/templates/inventario/crear_extintor.html
{% extends 'base.html' %}
{% block title %}Agregar Item{% endblock %}
{% block content %}
<div class="container mt-4 form-container">
    <h2>Agregar Nuevo Extintor</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}

        <div class="form-group">
            <label for="id_nombre">Nombre:</label>
            {{ form.nombre.errors }}
            {{ form.nombre }}
        </div>

        <div class="form-group">
            <label for="id_tipo">Tipo:</label>
            {{ form.tipo.errors }}
            {{ form.tipo }}
        </div>

        <div class="form-group">
            <label for="id_cantidad">Cantidad:</label>
            {{ form.cantidad.errors }}
            {{ form.cantidad }}
        </div>

        <button type="submit" class="btn btn-primary">Guardar Item</button>
    </form>
</div>
{% endblock %}

inventario/templates/inventario/detalle_extintor.html
{% extends 'base.html' %}
{% block title %}{{ extintor.nombre }}{% endblock %}
{% block content %}
<div class="container mt-4 form-container">
    <h2>Detalles de {{ extintor.nombre }}</h2>
    <hr>
    <p><strong>Nombre:</strong> {{ extintor.nombre }}</p>
    <p><strong>Tipo:</strong> {{ extintor.tipo }}</p>
    <p><strong>Cantidad:</strong> {{ extintor.cantidad }}</p>


    {% if request.user.is_authenticated and request.user.perfil.rol == 'administrador' or request.user.perfil.rol == 'tecnico' %}
        <a href="{% url 'inventario:editar_extintor' extintor.pk %}" class="btn btn-primary">Editar item</a>
    {% endif %}
    <a href="{% url 'inventario:inventario_home' %}" class="btn btn-link">Volver a la lista de items</a>
</div>
{% endblock %}

inventario/templates/inventario/editar_extintor.html
{% extends 'base.html' %}
{% block title %}Editar Item{% endblock %}
{% block content %}
<div class="container mt-4 form-container">
    <h2>Editar Item</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}

        <div class="form-group">
            <label for="id_nombre">Nombre:</label>
            {{ form.nombre.errors }}
            {{ form.nombre }}
        </div>
        
        <div class="form-group">
            <label for="id_tipo">Tipo:</label>
            {{ form.tipo.errors }}
            {{ form.tipo }}
        </div>

        <div class="form-group">
            <label for="id_cantidad">Cantidad:</label>
            {{ form.cantidad.errors }}
            {{ form.cantidad }}
        </div>

        <button type="submit" class="btn btn-primary">Guardar Cambios</button>
    </form>
</div>
{% endblock %}

inventario/templates/inventario/inventario_home.html
{% extends 'base.html' %}
{% block title %}Inventario{% endblock %}
{% block content %}

<div class="container mt-4 form-container">
    {% if messages %}
        {% for message in messages %}
            {% if 'inventario' in message.tags %}
                <div class="alert alert-success" role="alert">
                    {{ message }}
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}

    <h2>Lista de Extintores</h2>
    {% if request.user.is_authenticated %}
        {% if request.user.perfil.rol == 'tecnico' or request.user.perfil.rol == 'administrador' %}
            <a href="{% url 'inventario:crear_extintor' %}" class="btn btn-success mb-3">Agregar Item</a>
            <a href="{% url 'inventario:seleccionar_crud_inventario' %}" class="btn btn-info">Volver a la Gestión de Inventario</a>
        {% endif %}
    {% endif %}
    
    <form method="get" class="mb-3">
        <input type="text" name="q" class="form-control" placeholder="Buscar extintor..." value="{{ q }}">
        <button type="submit" class="btn btn-primary mt-2">Buscar</button>
    </form>

    {% for extintor in extintores %}
        <div class="card mb-3 caja-extintor">
            <div class="card-body">
                <h5 class="card-title">Nombre: {{ extintor.nombre }}</h5>
                <p class="card-text">
                    Tipo: {{ extintor.tipo }} <br>
                    Cantidad: {{ extintor.cantidad }}
                </p>
                {% if request.user.perfil.rol == 'administrador' or request.user.perfil.rol == 'tecnico' %}
                    <div class="container mt-4">
                        <form method="post" action="{% url 'inventario:eliminar_extintor' extintor.pk %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Eliminar</button>
                        </form>
                    </div>
                {% endif %}

                <a href="{% url 'inventario:detalle_extintor' extintor.pk %}" class="btn btn-primary">Ver Detalles</a>
            </div>
        </div>
    {% empty %}
        <p>No hay extintores disponibles en el inventario.</p>
    {% endfor %}
</div>
{% endblock %}

inventario/templates/inventario/seleccionar_crud_inventario.html
{% extends 'base.html' %}
{% block title %}Menú de Inventario{% endblock %}
{% block content %}


<div class="form-container">
    <h2>Seleccione una acción</h2>
    <p>Elija una de las siguientes acciones para gestionar el Inventario:</p>
    
    <div class="d-flex justify-content-around mt-4">
        <a href="{% url 'inventario:crear_extintor' %}" class="btn btn-success">Crear Item</a>
       
        <a href="{% url 'inventario:inventario_home' %}" class="btn btn-primary">Ver Items (Permite elminar y editar datos)</a>
       
    </div>
</div>


{% endblock %}