pedidos/urls.py
from django.urls import path
from . import views

app_name = 'pedidos'

urlpatterns = [
    path('', views.pedido_home, name='home'),

    path('seleccionarCrud/', views.seleccionar_crud_pedido, name='seleccionar_crud_pedido'),

    path('crear-pedido/', views.crear_pedido, name='crear_pedido'),
    path('lista-pedidos/', views.pedido_home, name='pedido_home'),
    path('editar-pedido/<int:pk>/', views.editar_pedido, name='editar_pedido'),
    path('detalle-pedido/<int:pk>/', views.detalle_pedido, name='detalle_pedido'),
    path('eliminar-pedido/<int:pedido_id>/', views.eliminar_pedido, name='eliminar_pedido'),
]

proyectoevaluacion/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usuarios.urls')),
    path('clientes/', include('Clientes.urls')),
    path('inventario/', include('inventario.urls')),
    path('pedidos/', include('pedidos.urls')),
    

]

usuarios/urls.py
from django.urls import path
from . import views

app_name = 'usuarios'

urlpatterns = [
    path('registro/', views.registro, name='registro'),
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('seleccionar-aplicacion/', views.seleccionar_aplicacion, name='seleccionar_aplicacion'),
    path('perfil/', views.perfil, name='perfil'),



]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Sitio Web{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <style>
        body {
            background-image: url("{% static 'images/fondo.jpg' %}");
            background-size: cover;
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-position: center;
        }
    </style>


</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
        <div class="container">
            <a class="navbar-brand" href="{% url 'usuarios:index' %}">
                <img src="{% static 'images/logo01.png' %}" alt="" height="50px" width="50px" class="mr-2">
                Exteamllamas
            </a> 
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarContent">
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                            {% if user.perfil.rol == 'administrador' %}
                            <a class="dropdown-item" href="{% url 'admin:index' %}">Panel de Admin</a>
                            {% endif %}
                            {% if user.perfil.rol == 'tecnico' or user.perfil.rol == 'administrador' %}
                            <a class="dropdown-item" href="{% url 'usuarios:seleccionar_aplicacion' %}">Panel de Gestión</a>
                            {% endif %}
                            <a class="dropdown-item" href="{% url 'usuarios:perfil' %}">Mi Perfil</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'usuarios:logout' %}">Cerrar Sesión</a>
                        </div>
                    </li>
                    {% else %}
                    <li class="nav-item ml-auto">
                        <a class="nav-link" href="{% url 'usuarios:login' %}">Iniciar Sesión</a>
                    </li>
                    <li class="nav-item ml-auto">
                        <a class="nav-link" href="{% url 'usuarios:registro' %}">Registrarse</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="container mt-4">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>